### ISSUE TITLE
BeffsBrowser 2.0 doesn't work properly on the Windows 10 Creators Update.

### ISSUE THREAD

**Issue by DrewNaylor** [jdc20181/BeffsBrowser#19]
I've tried restarting BeffsBrowser via menu>Operations>RestartBeffsBrowser. I would test the latest commit but I don't know how to build it. I've also tried new copies downloaded straight from the Releases page.

I've downloaded the latest stable version and tried running it in a VirtualBox VM (Windows 10 Pro build 15063.413 64-bit) without installing it first by running "BeffsBrowser.exe" and clicking on the "BeffsBrowser" button in the resulting menu. As soon as the main browser window appeared, the .Net Framework complained about an unhandled exception as seen below.

BeffsBrowser not installed:
![issue1-cannot-find-xul](https://user-images.githubusercontent.com/15517419/27981805-26e3ccb8-6360-11e7-9e3d-900e0a8cf0f1.PNG)

Text from the Details box before install:
<details>

Before installing BeffsBrowser:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.DllNotFoundException: Unable to load DLL 'xul': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Gecko.Xpcom.NS_InitXPCOM2(nsIServiceManager& serviceManager, Object binDirectory, nsIDirectoryServiceProvider appFileLocationProvider)
   at Gecko.Xpcom.Initialize(String binDirectory)
   at Gecko.Xpcom.Initialize()
   at Gecko.GeckoWebBrowser.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at Gecko.GeckoWebBrowser.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
BeffsBrowser
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/Drew/Desktop/VBOXSVRBeffsBrowserVersion2.0/program%20files/BeffsBrowser/BeffsBrowser/BeffsBrowser.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
Geckofx-Winforms
    Assembly Version: 45.0.6.0
    Win32 Version: 45.0.6.0
    CodeBase: file:///C:/Users/Drew/Desktop/VBOXSVRBeffsBrowserVersion2.0/program%20files/BeffsBrowser/BeffsBrowser/Geckofx-Winforms.DLL
----------------------------------------
Geckofx-Core
    Assembly Version: 45.0.6.0
    Win32 Version: 45.0.6.0
    CodeBase: file:///C:/Users/Drew/Desktop/VBOXSVRBeffsBrowserVersion2.0/program%20files/BeffsBrowser/BeffsBrowser/Geckofx-Core.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

</details>

However, if I install it first by running the "BeffsBrowser.msi" file then run the EXE from earlier (or from the "BeffsBrowser" Program Files (x86) folder), I get an error about a program being in an incorrect format as seen below.

BeffsBrowser installed:
![issue2-incorrect-program-format](https://user-images.githubusercontent.com/15517419/27981897-a42e06dc-6362-11e7-8165-29f7a430e3d2.PNG)

Text from the Details box after install:

<details>

After installing BeffsBrowser:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at Gecko.Xpcom.NS_InitXPCOM2(nsIServiceManager& serviceManager, Object binDirectory, nsIDirectoryServiceProvider appFileLocationProvider)
   at Gecko.Xpcom.Initialize(String binDirectory)
   at Gecko.Xpcom.Initialize()
   at Gecko.GeckoWebBrowser.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at Gecko.GeckoWebBrowser.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
BeffsBrowser
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/Drew/Desktop/VBOXSVRBeffsBrowserVersion2.0/program%20files/BeffsBrowser/BeffsBrowser/BeffsBrowser.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
Geckofx-Winforms
    Assembly Version: 45.0.6.0
    Win32 Version: 45.0.6.0
    CodeBase: file:///C:/Users/Drew/Desktop/VBOXSVRBeffsBrowserVersion2.0/program%20files/BeffsBrowser/BeffsBrowser/Geckofx-Winforms.DLL
----------------------------------------
Geckofx-Core
    Assembly Version: 45.0.6.0
    Win32 Version: 45.0.6.0
    CodeBase: file:///C:/Users/Drew/Desktop/VBOXSVRBeffsBrowserVersion2.0/program%20files/BeffsBrowser/BeffsBrowser/Geckofx-Core.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```
</details>

Here's what it looks like after clicking Continue in those error messages:

![issue3-no-browser-control](https://user-images.githubusercontent.com/15517419/27982250-73aaff84-636b-11e7-9b86-c0f3867f5f3d.PNG)

The progress bar is in a permanently indeterminate state when this problem occurs as well.

I figured that maybe installing Firefox would help in case there was a file that was used from the Firefox folder if it was installed, but that didn't help. I've also tried a reboot and that didn't help either.

This issue also seems to affect "Tappy Bird" in the "Arcade" window, as well as navigating to favorites via the "Favorites" button on the main window. Opening another tab via the new tab button on the toolbar also presents this issue. So far I haven't found any other places where this problem occurs.

The main reason I wanted to try out BeffsBrowser is to see how smooth GeckoFX worked and if it crashed with >80 tabs.

What's really strange is there's an "xul.dll" file in the same folder as "BeffsBrowser.exe" even though .Net says it can't find it.

Once BeffsBrowser is uninstalled, the first error shows up when trying to run it. If I reinstall it, the second error shows up.

If more info is required, I'll provide it.

**Comment by jdc20181** [comment]
Make sure you have the latest release, I do not get this error on my
windows 10 machine. You have to install it you can't just run the .exe
without installing because of the history files and components.

An easy fix if the files appear there -
Paste them in the path where it's trying to find them. I had no issues with
it on my computer.

I'll see what I can do for a fix as of now I'm having deployment issues
since Installshield isn't available for VS17.

Usually you can ignore those errors and it will go on. But I do not know.

(see below for more details)

**Comment by jdc20181** [comment]
Everything is working fine here, I checked again, just to be sure. 

As for needing firefox, that isn't neccessary, unlike needing Internet explorer, the DLL's are all included that make Gecko work. 

The correct installer is highlighted in the following screenshot: 

https://1drv.ms/i/s!ApbxWlyVVDT2g3m6I8xLgtdimlNA

I have gotten this same error before, so it isn't impossible to get it. However, I only got it once and couldn't recreate the issue - only difference was mine was occuring with the context menu. 

And just a FYI, the reload button doesn't work, apparently that needed to be changed, as it don't work with gecko. 

As far as building the source, you can't really, unless you know what is what, the only valuable pieces of my code are what makes things work. 

I compile everything in VS, and (did) use Installshield, but now that it isn't supported with vs 17 I am uncertain, about the future deployment of BB

**Comment by DrewNaylor** [comment]
I made a new 32-bit Windows 10 Pro build 15063 VM just in case there was a problem with not all the assemblies being built for AnyCPU  [as some people have mentioned online](https://stackoverflow.com/questions/18007967/net-framework-error-hresult-0x8007000b), but that didn't help either. When testing BeffsBrowser in the new install, I only installed from the MSI then launched from the Start menu. In a moment I will post something else I figured out...

**Comment by DrewNaylor** [comment]
Edit 1: I typed "msvcp.dll" at the end instead of "msvcp120.dll," so I fixed it.

As you probably know, in the "Version2.0.zip" file on the Releases page that contains BeffsBrowser, there's a "System32" folder with some DLLs:

![solution1-beffsbrowser-zip-file-system32-dlls](https://user-images.githubusercontent.com/15517419/27989170-e7695d2c-6400-11e7-97e9-1dbe24fed05c.PNG)

 The important ones are "msvcp120.dll" and "msvcr120.dll." "vccorlib120.dll" doesn't seem important for what I figured out.

Once BeffsBrowser is installed, these two files are copied into the "Windows\System32" directory on the machine:

![solution2-breaking-dlls-in-system32](https://user-images.githubusercontent.com/15517419/27989209-0b77ea52-6402-11e7-9398-7079866ed2b5.PNG)

I just copied those files over to demonstrate, but the result is the same if I had installed BeffsBrowser from the MSI.

I then relaunch BeffsBrowser from the extracted Zip file downloaded from the Releases page (under "program files\BeffsBrowser\BeffsBrowser\BeffsBrowser.exe") with the DLLs copied into "Windows\System32" and .Net gives me another incorrect format exception:

![solution3-dll-incorrect-format](https://user-images.githubusercontent.com/15517419/27989265-f5a95f7a-6402-11e7-9531-195d8baf3eb6.PNG)

While I was searching for those two DLLs from earlier (to overwrite the ones BeffsBrowser installs just in case that was the problem) I discovered two DLLs with a similar file name but with a few more characters:

![solution4-other-dlls-different-name](https://user-images.githubusercontent.com/15517419/27989425-45e43a84-6406-11e7-918a-ad83e10ab1c3.PNG)

I then decided to just copy/paste them in the "Windows\System32" folder and rename them to be the same as the ones provided by BeffsBrowser:

![solution5-renamed-dlls](https://user-images.githubusercontent.com/15517419/27989430-809fe024-6406-11e7-8cd1-f510d0969e50.PNG)

The original files I copied from are "msvcr120_0400.dll" and "msvcp_0400.dll."

What happens if we then run BeffsBrowser from the extracted Zip file? Well, if you're connected to the internet, the homepage loads up! See below:

![solution6-beffsbrowser-working](https://user-images.githubusercontent.com/15517419/27989617-a3c3a23a-640a-11e7-89b7-27a65d461f3c.PNG)

This method seems to fix BeffsBrowser on 32-bit Windows, but not 64-bit Windows. To fix it on 64-bit Windows, those DLLs have to be copied/pasted/renamed in the "Windows\SysWOW64" folder instead. Copying the DLLs from "Windows\System32" to "Windows\SysWOW64" on a 64-bit Windows install breaks BeffsBrowser.

I've tried replacing the DLLs provided with BeffsBrowser with the renamed/copied ones from earlier before installing it with the MSI and that also seems to work even if I delete both DLLs from "Windows\System32" before installing. On 64-bit Windows, DLLs have to be copied/renamed from "Windows\SysWOW64" to the BeffsBrowser System32 folder before installing BeffsBrowser and it'll work.

The reason why it works on your computer may be due to Visual Studio being on your PC as I also have the "msvcr120.dll" and "msvcp120.dll" files in both my "Windows\System32" and my "Windows\SysWOW64" folders on my main PC with 64-bit Windows 7 and Visual Studio 2015.

**Comment by jdc20181** [comment]
I installed BB on my new machine before I got VS, as I originally built and
developed it on my other machine.

And I never had those issues but I don't know if it's 64 rather it may be a
86x so I am uncertain what would be causing the hang up.

I build BB on Any CPU because previously some of my code wouldn't build on
anything else.

I will try to get to the bottom of it. I have ran it on Windows 7 but again
most likely x86 rather than 64x it could be that x64 isn't supported by
Gecko. this is a interesting issue. I'll work on it, I am still dealing
with deployment issues, as I can't use Installshield.

Thanks again,

We will work together sometime soon

**Comment by DrewNaylor** [comment]
I just realized that one reason why it doesn't crash on your PC is because yours could have the Visual C++ Redistributable installed, though I don't know.

I usually build on AnyCPU as well.

What's really strange about all this is, Firefox runs just fine while also using xul/Gecko I'm pretty sure. Could be something is trying to use the incorrect DLL.

Have you tried using NSIS or InnoSetup for making an installer? I haven't personally made a real installer with either one, but I've heard that NSIS is more powerful than InnoSetup.

**Comment by jdc20181** [comment]
I have tried those they aren't the best. I don't like the UI

**Comment by jdc20181** [comment]
My  "answer" to resolving is that it just isn't compatible with X64 - Which is a bummer. I am going to look into this more, and get a more final ruling. At this point I can't rule out compatibility.  But I will investigate further to see what I can come up with.

**Comment by jdc20181** [comment]
When using the standard build and deploy with VS I got xul error, this is a dependency of Gecko. Why it isn't being included is beyond what I can understand.

**Comment by DrewNaylor** [comment]
xul.dll is in the same folder as BeffsBrowser.exe, so that's just a red herring:

![solution7-beffsbrowserexe-xuldll](https://user-images.githubusercontent.com/15517419/27997590-7ac422dc-64c9-11e7-892e-99c302ccc6b4.PNG)

I've tested installing the x86 [Visual C++ 2013 Redistributable Package](https://support.microsoft.com/en-us/help/3179560/update-for-visual-c-2013-and-visual-c-redistributable-package) on an x64 Windows install and it installs the correct files to SysWOW64 and BeffsBrowser works, similar to how I copied/pasted/renamed the DLLs yesterday. I'll have to check installing this on an x86 Windows install and see what happens.

I've also uninstalled the package and just copied the necessary DLLs to the BeffsBrowser folder and it still worked, so that's also an option although the DLLs have to be from the x86 Redistributable:

![solution8-copy-dlls-beffsbrowser-folder](https://user-images.githubusercontent.com/15517419/27997741-08222310-64cd-11e7-97a3-de6478082587.PNG)

If the DLLs from the x64 Redistributable are used instead, .Net complains about an invalid format error like it did before.

**Comment by DrewNaylor** [comment]
I've just tested this in my 32-bit Windows 10 VM and it does fix both of the errors in my first comment on this issue.

There are two ways to fix this:

- Copy the 32-bit "msvcr120.dll" and "msvcp120.dll" files from "Windows\System32" on a 32-bit install or from "Windows\SysWOW64" on a 64-bit install into the same folder as "BeffsBrowser.exe."

- Make the x86 [Visual C++ 2013 Redistributable Package](https://support.microsoft.com/en-us/help/3179560/update-for-visual-c-2013-and-visual-c-redistributable-package) a system requirement for running BeffsBrowser.

If it was up to me, I'd include those DLLs in the folder with "BeffsBrowser.exe" in the next release and in the meantime, direct people to download and install the x86 VC++ 2013 Redist package.

The reason why copying the files to the same folder as "BeffsBrowser.exe" works is because of how Windows works for some things: If there's a DLL in the same folder as the file requesting it, Windows will use that DLL. Otherwise, if that file is missing, Windows will just use the DLL from either System32 or SysWOW64, depending on whether or not the program asking for the file is 32-bit or 64-bit.

**Comment by jdc20181** [comment]
Wonder what's depending on the Redist of VC++? Many machines should have
this installed since it's a common dependency. I will give you some more
details later. I am working on a new release it's just rough because of
Installshield not being available.

**Comment by DrewNaylor** [comment]
It's probably GeckoFX since BeffsBrowser itself is VB according to the project description.

**Comment by jdc20181** [comment]
As soon as I get a decent installer solution going, and get the 2.1.0 release out, I am going to look for and work on some fixes.

**Comment by DrewNaylor** [comment]
Ok. Hopefully you'll be able to get a good installer method.

**Comment by jdc20181** [comment]
@DrewNaylor See in the new release if it fixes the issues. Let me know. Oh and make sure all of the previous version is manually removed. 

I am using advance installer, I emailed them about getting a free license, right now I am using the freeware portion of the software. Best of all it isn't tied to VS.

*Fixed installer will be ready at end of day I missed something important*

*Fixed the installer*

**Comment by DrewNaylor** [comment]
I've tried the new installer for 2.1 in both 32-bit and 64-bit Windows 10 VMs with snapshots from before I previously tried BeffsBrowser and it does work on both of them.

BeffsBrowser is no longer broken on clean installs since msvcr120.dll and msvcp120.dll are in the same folder as BeffsBrowser.exe. I'll close this issue since it's fixed.

Thank you for your time and cooperation.

Also, the installer does work pretty well.

If you have any more questions or need me to test anything, let me know.

**Comment by jdc20181** [comment]
BB is compatible with all systems Windows 7 and newer, I am working on a
separate version for Windows 10 which is just the Newest .Net Framework so
even if you didn't have Windows 10 and had the requirements for the .net
framework it requires you will be fine.

Thanks for your help and yes most likely I will need more testing in the
future, continue to use, and reuse Beffsbrowser, I will be committing more
on your project.

Thanks.

jdc20181

**Comment by DrewNaylor** [comment]
You're welcome.
