### ISSUE TITLE
Win10 IoT

### ISSUE THREAD

**Issue by InteXX** [jdc20181/BeffsBrowser#28]
I'm very interested in attempting to adapt this code for Win10 IoT (running on the Raspberry Pi 3). I hope to be able to use it to authenticate to a website and download an authorized file to a user-specified folder.

Can you foresee any issues, trouble spots?

**Comment by jdc20181** [comment]
Really depends on the compatibility of using the .NET framework. As long as it can run freely, you shouldn't have any issues adapting the code from here. But please note you will need the GeckoFX Nuget Package, I used a forked version, that is more easily adapted to the .net framework. Most of everything is done from code, but the larger package was too much to maintain and adapt. There is also a slight issue with a config file with the nuget package, I forgot what the error was exactly but it was pretty easy to fix, the solution was posted on vbforums. (If I have time later to search for it I will link to it here)

**Comment by InteXX** [comment]
Very good, thank you.

Specifically, does BeffsBrowser handle file downloads?

**Comment by jdc20181** [comment]
As an application it is still touch and go with files, I just haven’t had
time to put the effort into handling files. It shouldn’t be hard- most of
the C# examples for Gecko work in vb with modifications. I’ll try to whip
up a solution as soon as I am free.

**Comment by InteXX** [comment]
It's an adventure living in a C# world, isn't it?  ;-)

I wish you wouldn't go to a lot of trouble...  this is very much a side project of mine. I'm going to be taking it very slowly.

**Comment by jdc20181** [comment]
I think I have a few solutions to test and see how they go. Will try to get in the next update, if not it will be after (Which is about finished). < 3 months from now.

**Comment by InteXX** [comment]
That sounds about right.

**Comment by jdc20181** [comment]
So far no luck on implementing proper handles, but it looks like it does download files, and saves them to your downloads folder. It seems to hang up when you navigate to a downloadable file e.g. .zip .pdf etc.

**Comment by InteXX** [comment]
My (admittedly naive) theory is to:
1. Somehow detect a click
2. Somehow get the URL that was clicked
3. If the MIME type indicates a file (.zip, .pdf etc.), present some sort of custom file picker dialog
4. Pass the dialog result off to a WebClient instance

Would this be a satisfactory high-level approach?

**Comment by jdc20181** [comment]
Looks like it’s the easiest approach. Would use a web client. Windows has
the shell type of Internet Explorer readily available, and it handles
downloads a bit better. But a web client request would be a bit more
“independent” and less reliable on 3rd party technology

**Comment by InteXX** [comment]
And, for my purposes at least, this all has to run on a limited subset of UWP. Given this, I'm probably over-simplifying—but that's a bridge to cross when I get there.

**Comment by jdc20181** [comment]
Ah. This project compiles into a .NET *.exe
Most Windows Store apps run with edge.

**Comment by InteXX** [comment]
> Most Windows Store apps run with edge

Yes, I see that others have made UWP browsers using the WebView control. When I get around to working on this, though, I'd like to try yours first (not the .exe, but at least the source).

**Comment by jdc20181** [comment]
To build using source - You will need the [Nuget](https://www.nuget.org/packages/GeckoFX/) package, and you will need to modify one of the files as described [here](http://www.vbforums.com/showthread.php?849501-RESOLVED-Strange-error-(New-to-VS-17-porting-from-VS-13)&highlight=Strange)

Everything else should work alright, don't use too new of the .NET Framework. Stick with 4.0 or 4.5 


You will get an error when you first insert the nuget package, upon editing of the file described in the linked post, do a clean, and a rebuild. After that it should remove any errors.

**Comment by InteXX** [comment]
Got it, thanks.

**Comment by InteXX** [comment]
FYI I've decided to abandon the effort to get a browser running on Win10 IoT on rPI.

I was getting soft on the idea already, but then I came across [this](https://www.codeproject.com/Tips/1392482/Windows-10-IoT-Core-on-Raspberry-Pi-4-2019-update):

> We ended up displaying very [simple] web page, and even that was not reliable engough, because after some time (6 - 7 months) our raspberries start to [break] down because of high CPU usage and overheating.

That one pretty much buried the hatchet.

**Comment by jdc20181** [comment]
Beffsbrowser was just a fun project of mine not really to get a lot of
users, I am however rebuilding from scratch, and am going to explore better
support for more platforms. I’ll let you know what happens!

**Comment by InteXX** [comment]
Big things come from small beginnings  :-)
